// API
export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'

export const USERNOTIFICATION_LIST = '@@INCONNECT/USERNOTIFICATION_LIST'
export const LOAD_USERNOTIFICATIONS = '@@INCONNECT/LOAD_USERNOTIFICATIONS'
